### ISSUE TITLE
Set 'size' property incorrectly transpiled as 'length' in typescript

### ISSUE THREAD

**Issue by Ben-Johnson-ck** [creditkarma/scrooge#10]
See title.

### Expected behavior

Set<> should use 'size'.

### Actual behavior

Set<> uses 'length'.

### Steps to reproduce the behavior

Run generator on any thrift file containing a set<___>.

**Comment by ian-harshman-ck** [comment]
Fixed in 3cde5e48f1852c302847e52791c8e6e98404d96e
